### ISSUE TITLE
Allow to specify which mappings are used for which purpose in Request

### ISSUE THREAD

**Issue by irizzant** [crossplane-contrib/provider-http#58]
### What problem are you facing?

As far as I can understand `Request` works with this logic:
* Use GET request for reconciliation to verify if the resource is created
* If absent send a POST request
* If changed send a PUT request

While this is an opinionated standard it would be good to allow to choose the HTTP method to use for each purpose.

E.g.
I have this API
https://api.getport.io/static/index.html#/Users

To create a User a need to send a POST to [/v1/users/invite](https://api.getport.io/static/index.html#/Users/post_v1_users_invite).
To update a PATCH to [/v1/users/{user_email}](https://api.getport.io/static/index.html#/Users/patch_v1_users__user_email_)
To get an existing User a GET to [/v1/users/{user_email}](https://api.getport.io/static/index.html#/Users/get_v1_users__user_email_)

It would be great being able to map these in the `mappings` field.

**Comment by miguellobato84** [comment]
I think the mappings, instead of being HTTP verbs, should represent actions (CREATE, UPDATE, INFO, REMOVE), and the HTTP method used should be just another attribute, like the URL or the body.

This way, it would be generic enough for any API.

**Comment by arielsepton** [comment]
I think this is a great idea!

I want to avoid breaking the existing API, but I’ll look into how to add this feature soon.

Thank you for the suggestion—it would definitely make managing various APIs easier!

**Comment by miguellobato84** [comment]
just saw your PR, thanks!

**Comment by irizzant** [comment]
Thank you! When is the next release expected?
