### ISSUE TITLE
Request object / expected response in GET

### ISSUE THREAD

**Issue by miguellobato84** [crossplane-contrib/provider-http#59]
What problem are you facing?
We are encountering an issue with the API we are trying to manage; it returns different response bodies for the GET and PUT requests. When using the Request object, this discrepancy causes it to get stuck in a loop.

To address this issue, it would be greatly beneficial to have an optional “expected response” field in the GET object. By default, this could align with the body of the PUT mapping.

Thank you for considering this enhancement!

**Comment by arielsepton** [comment]
I understand the issue you’re facing. My only concern is potential confusion during resource updates—you’d update the `PUT` mapping for the request execution but would also need to update the `expected response` separately. This could lead to data inconsistencies—updating the same information in different places, which can complicate management.

Currently, the `PUT` mapping’s body only needs to be contained within the `GET` response, not an exact match. Does that still not meet your needs?

**Comment by miguellobato84** [comment]
yeah.. not the best API implementation :(

what about a jq expression that allows to transform the PUT response?

**Comment by arielsepton** [comment]
I understand what you’re suggesting, but just to clarify—right now, you can already apply any jq expression to transform the PUT body. The only requirement is that the result of this expression should either be contained within the GET response or used as the body of a PUT request if it’s not.

Does that address your concern, or are you thinking of a different type of transformation? Let me know if I’m missing something!

**Comment by miguellobato84** [comment]
great, thanks!
